### PR TITLE
Add missing materials.

### PR DESCRIPTION
**Pull request by CanExiOne**
Add missing materials to the ``Gathering`` config. I also moved around other mats so they are sorted by type, it wasn't necessary but it was really bugging me.

Added materials:
- Yggdrasil Wood
- Black Marble
- Copper Scrap

### CODE REVIEW

**Comment by CanExiOne** [comment]
Added [963429f](https://github.com/Grantapher/ValheimPlus/pull/18/commits/963429ff6ac0ef8d744c431e61fce0ced10fc13f) to fix #15.

**Review by Grantapher — APPROVED** [review]
I'll clean this up myself, just minor things:
* removing blank line in PickableConfiguration
* re-formatting DropTable to use tabs only
* rearranging comments in config file, removing unnecessary whitespace

**Comment by Grantapher** [comment]
cherry-picked onto grantapher-development and then cleaned up in 91da71e.

**Comment by Grantapher** [comment]
Released into [`0.9.11.0`](https://github.com/Grantapher/ValheimPlus/releases/tag/0.9.11.0).

**Pull request merged**
